version: '3.8'
services:
  web:
    container_name: myhotel-challenge-app
    restart: always
    build:
      context: ..
      dockerfile: Dockerfile
    image: web:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_ROOT_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    container_name: myhotel-challenge-database
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
    ports:
      - '3306:3306'
    volumes:
      - ./database/tmp:/var/lib/mysql:rw
      - ./database/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
volumes:
  database:
    driver: local